VERSION_NUMBER = "1.0.0-SNAPSHOT"
GROUP = 'barreverte.fr'
COPYRIGHT = 'Barre Verte !'

repositories.remote << 'http://www.ibiblio.org/maven2/'
repositories.remote << 'http://maven01b.int33.cvf:8081/nexus/content/groups/public'

desc 'a buildr example'
define 'example' do
  project.version = VERSION_NUMBER
  project.group = GROUP

  compile.using :target=>'1.5', :other=>['-encoding', 'ISO8859_1'], :deprecation=>false, :debug=>true

	desc 'lib A'
	define 'A' do
		package :jar
	end

	desc 'lib B'
	define 'B' do
		compile.with project('A')
		package :jar
	end

	desc 'lib D'
	define 'D' do
		package :jar
	end

	desc 'my deliverable'
	define 'C' do
		compile.with projects('A', 'B', 'D')
		package :war
	end
end
