VERSION_NUMBER = '1.2.0-SNAPSHOT'
GROUP = 'barreverte.fr'
COPYRIGHT = 'Barre Verte !'

repositories.remote << 'http://www.ibiblio.org/maven2/'
repositories.remote << 'http://maven01b.int33.cvf:8081/nexus/content/groups/public'

repositories.release_to[:url] = if VERSION_NUMBER =~ /SNAPSHOT/
  'http://maven.target2sell.com/content/repositories/snapshots/'
else
  'http://maven.target2sell.com/content/repositories/releases/'
end

Release.next_version = lambda do |this_version|
  new_version = VERSION_NUMBER.split /\./
  new_version[1] = new_version[1].to_i + 1
  new_version
end

desc 'presentation buildr'
define 'exemple' do
  project.version = VERSION_NUMBER
  project.group = GROUP

  compile.using :source => '1.5', :target=>'1.5', :other=>['-encoding', 'ISO8859_1'], :deprecation=>false, :debug=>true

	desc 'la lib A'
	define 'A' do
		package :jar
	end

	desc 'la lib B'
	define 'B' do
		compile.with project('A')
		package :jar
	end

	desc 'la lib D'
	define 'D' do
		package :jar
	end

	desc 'mon livrable final'
	define 'C' do
		compile.with projects('A', 'B', 'D')
		package :war
	end
end
